### ISSUE TITLE
how can I run this without barcodes

### ISSUE THREAD

**Issue by splaisan** [aramette/LORCAN#1]
Can you please show an example of sample_id.txt for a run without barcode.
My 'amplicons' have been produced without using the ONT kit and they do not have barcodes.
In fact they have not been made by PCR but instead extracted from gDNA reads thereby not having any additional sequence besides the 16S amplicon region (https://github.com/Nucleomics-VIB/InSilico_PCR/blob/master/ZymoPromethion_even_Results.md)

**Comment by aramette** [comment]
Currently the script only handles sequencing data provided they were sequenced with ONT kits. The porechop step trims the sequences based on the barcode and adapter sequences found in the reads. Given the data you indicated, I am not sure that the LORCAN pipeline is the correct tool for your application. Quick fix: Either you could add artificially add some fake barcode sequences to the reads, or you could skip the first steps of the pipeline by modifying the script itself (by commenting the steps that are doing the barcode and adapter identification).
