### ISSUE TITLE
Empty file generated at R3_test

### ISSUE THREAD

**Issue by leocaserta** [aramette/LORCAN#2]
Hello 
I tried LORCAN for the first time and after around 30 minutes i recceived an error message. My command and the error message are described below. Besides the "Empty file generated at R3_test" there was also "sh: parallel: command not found". 
Do you have any idea for the reason and solution of this error? 
Thank you!

LORCAN -V -i /home/lcc88/Desktop/PRRSV/PRRSV_serum_03_18_20/basecalled_40min -o /home/lcc88/Desktop/PRRSV/PRRSV_serum_03_18_20 -L log_main.txt -I /home/lcc88/Desktop/PRRSV/PRRSV_serum_03_18_20/Sample_id_PRRSV_serum_ISU_03_18_20_ampliseq.txt -n 24 -m 10 -M 5000 -P 10 -D 5 -d PRRSV_dp_LORCAN
OK: all arguments are present
current working directory: /home/lcc88/LORCAN/LORCAN/1.8/lib
        (i) readDIR:           /home/lcc88/Desktop/PRRSV/PRRSV_serum_03_18_20/basecalled_40min
        (I) sampleID:          /home/lcc88/Desktop/PRRSV/PRRSV_serum_03_18_20/Sample_id_PRRSV_serum_ISU_03_18_20_ampliseq.txt
        (o) Cdir:              /home/lcc88/Desktop/PRRSV/PRRSV_serum_03_18_20
        (L) Main log name:     log_main.txt
        (n) NberThreads:       24
        (m) Min nber reads per BC: 10
        (M) Consensus MaxRead: 5000
        (P) Consensus MinRead: 10
        (D) delta:             5
        (d) DBchoice:          PRRSV_dp_LORCAN
=> (R0_Checking script dependencies) already completed
=> running R1_Seqkit...
sh: parallel: command not found
=> running R2_porechop...
=> running R3_Seqkit_after_porechop...
sh: parallel: command not found
!!! Empty file generated at R3_test:
/home/lcc88/Desktop/PRRSV/PRRSV_serum_03_18_20/0_logs/2_stats_fastq_postporechop.txt (exit!)

**Comment by aramette** [comment]
Hi,
It seems that your system is missing one of the parallelization module called by _LORCAN.pl_.
On which system are you running?
What does this command line return?
_man parallel_
If you obtain a help page, it means that Gnu parallel is installed. Otherwise, please install Gnu parallel on your system.

**Comment by leocaserta** [comment]
Hi 
Thank you for your response. I am running on Linux (HPC cloud). The cloud has GNU parallel installed in it. 
In this case, should i replace the path to perl parallel by the path to GNU parallel?:  
Actual path:
 our $PERL	="/home/lcc88/miniconda3/envs/LORCAN-env/bin/perl"; 

Path to GNU parallel:   
our $PERL	="/programs/parallel/bin/parallel"; 

? 

Thank you again

**Comment by aramette** [comment]
Hello,
$PERL should be pointing to your Perl binary, not to Gnu Parallel.
So 
`our $PERL ="/home/lcc88/miniconda3/envs/LORCAN-env/bin/perl";`
is probably correct.

If GNU parallel is installed (and _man parallel_ returns something meaningful; see previous message), 
then you are set and you can run the _LORCAN_ pipeline.

GNU parallel is needed at line 128 of: 
https://github.com/aramette/LORCAN/blob/master/1.8/lib/LORCAN_subs.pm
to parallelize the calculation of the seqkit stats call.
