### ISSUE TITLE
Tk::PNG not installed

### ISSUE THREAD

**Issue by leocaserta** [aramette/LORCAN#3]
Hello 
I managed to run LORCAN but now i receive the following message after checking for Prl module dependencies: 

(LORCAN-env) [lcc88@cbsumm01 lib]$ LORCAN -V -i subset_test -o results -L log_main.txt -I /home/lcc88/LORCAN/LORCAN/1.8/lib/Sample_id_PRRSV_serum_ISU_03_18_20_ampliseq.txt -n 24 -m 10 -M 5000 -P 10 -D 5 -d PRRSV_db_LORCAN
OK: all arguments are present
current working directory: /home/lcc88/LORCAN/LORCAN/1.8/lib
        (i) readDIR:           subset_test
        (I) sampleID:          /home/lcc88/LORCAN/LORCAN/1.8/lib/Sample_id_PRRSV_serum_ISU_03_18_20_ampliseq.txt
        (o) Cdir:              results
        (L) Main log name:     log_main.txt
        (n) NberThreads:       24
        (m) Min nber reads per BC: 10
        (M) Consensus MaxRead: 5000
        (P) Consensus MinRead: 10
        (D) delta:             5
        (d) DBchoice:          PRRSV_db_LORCAN
=> Checking script dependencies...
[ERRO] Network error
Checking db
        blastDBFile: PRRSV_db_LORCAN.fas
        blastDBFolder: /home/lcc88/LORCAN/LORCAN/1.8/lib/PRRSV_db/
Test db is ok (file found). Continuing...
Checking for Perl module dependencies:
OK               ... FindBin
OK               ... Cwd
OK               ... Parallel::ForkManager
OK               ... PDF::API2
not installed!!! ... Tk::PNG
Some Perl modules are not installed:
Exiting

I installed Tk in the Lorcan environment but i still receive the same message. How should i install Tk::PNG? 

Thank you 

Leonardo

**Comment by aramette** [comment]
Dear Leonardo,
I fixed the issue. The Tk::PNG is not needed. Please download the files again to have the latest version of the LORCAN_subs.pm in your library folder.
