### ISSUE TITLE
How to run with demultiplexed data ?

### ISSUE THREAD

**Issue by nbargues** [aramette/LORCAN#4]
Hi, I'm a bit confused on how you handle input data. 
Minion/Gridion/Promethion performed realtime-demultiplexing since a couple of years already. 
So I have ONT 16s data and I can't try your pipeline. Since the last similar issue with Mr Plaisance, do you have a fix/workaround for people with such data ? 

Thanks

**Comment by aramette** [comment]
Hello,
This is a good point, which has historical reasons: We assumed that not everybody has access to real-time demultiplexing on their machine due to CPU limitations and that most users will use MinION on a typical laptop or office desktop. Therefore the idea was to demultiplex the FASTQ files on a more powerful server in a second stage with LORCAN.
We will add the option to start from demultiplexed data from the beginning of the pipeline in the new LORCAN release. A fix for now is to merge your demultiplexed FASTQ into one file and put that file into an input folder, as expected by LORCAN. Also the new version uses qcat instead of porechop (so it is much much faster).
Best,
AR

**Comment by nbargues** [comment]
I have cat all my fastq from a run into one and run LORCAN. The pipeline failed to demultiplex.
Do you thinks it's because of some fastq header format ? Do you have an idea why ?

PS: When do you plan to release the new version of LORCAN ?

**Comment by aramette** [comment]
Hello,
I plan on releasing a new version with several new features in the next weeks. If you want you can also send me, small FASTQ file for me to check what may create the failure. By the way, can you describe what you obtain (error messages, log.txt) when you run the pipeline? It is not clear to me where the error comes from yet. Thanks.
Best,
Alban

**Comment by aramette** [comment]
You could also try with one of the FASTQ files, without merging all FASTQ to see if something is wrong with the headers indeed. The pipeline will not produce a consensus but at least you should see some statistics reflecting the low number of reads.

**Comment by nbargues** [comment]
[log_main.txt](https://github.com/aramette/LORCAN/files/5630537/log_main.txt)

Here is the log file.

**Comment by aramette** [comment]
Thanks. Looks to run fine from the log file apparently. You setup of the pipeline seems correct too.
From the log itself, i cannot see that it does not work.

Did you run the TEST section to validate that the pipeline is working correctly on the test data on your system? 
[test](https://github.com/aramette/LORCAN/tree/master/1.8#test)

**Comment by nbargues** [comment]
I just run the test on my system:
It seems that it's the DB that create an error. What do you think ? ( log and a report attach )
[BC17_report.pdf](https://github.com/aramette/LORCAN/files/5634608/BC17_report.pdf)
[log_main.txt](https://github.com/aramette/LORCAN/files/5634609/log_main.txt)

**Comment by aramette** [comment]
This is the expected output indeed for BC17. 
If you check the result table provided in the TEST section, you will see that
BC17:mysample2 | 54 | Not enough reads matching. No consensus was built for this sample.
So everything works fine at least for this barcode.

If you provide the PDF of another sample that is predicted to have enough reads to produce a consensus at the end of the pipeline, e.g. any of *BC16, BC19, BC24, BC25, BC28*, it would be easier to diagnose whether you have an issue with your config files, including db setup.

This is a copy of the results from the [TEST section](https://github.com/aramette/LORCAN/tree/master/1.8#TEST) in the README page:
 **BC16**:mysample1 | **148** | L=462 N=1 G=1 Taxo=**Mycobacterium_chimaera**
  **BC19**:mysample4 | **239** | L=462 N=0 G=1 Taxo=**Mycobacterium_intracellulare_subsp._intracellulare**
  **BC24**:mysample7 | **232** | L=462 N=1 G=1 Taxo=**Mycobacterium_intracellulare_subsp._intracellulare**
  **BC25**:mysample8 | **191** | L=462 N=0 G=1 Taxo=**Mycobacterium_intracellulare_subsp._intracellulare**
  **BC28**:mysample11 | **246** | L=483 N=0 G=0 Taxo=**Streptococcus_thermophilus**
  **BC29**:mysample12 | **272** | L=448 N=0 G=4 Taxo=**Corynebacterium_tuberculostearicum**
  **BC30**:mysample13 | **392** | L=448 N=0 G=4 Taxo=**Corynebacterium_tuberculostearicum**

Please refer to the [README](https://github.com/aramette/LORCAN/blob/master/1.8/README.md#lorcan-long-read-consensus-analysis) file to understand what the different numbers and symbols represent in the output above.

**Comment by nbargues** [comment]
In fact all the sample have the same result, even those you indicate.
[BC16_report.pdf](https://github.com/aramette/LORCAN/files/5635462/BC16_report.pdf)

So that means that I have wrongly install LORCAN ?

**Comment by aramette** [comment]
It seems that LORCAN is installed correctly. Otherwise, you would not have obtained a report and the program would have stopped earlier.
It seems that the FASTA sequences are not extracted correctly. 
Can you provide all the log files for BC16 that you can find in /0_logs/ please?

**Comment by nbargues** [comment]
Here : 
[2_stats_fastq_postporechop.txt](https://github.com/aramette/LORCAN/files/5635650/2_stats_fastq_postporechop.txt)
[3_Barcodes_with_modal_sequences.txt](https://github.com/aramette/LORCAN/files/5635654/3_Barcodes_with_modal_sequences.txt)

**Comment by aramette** [comment]
I think i know what happens:
In the report PDF, the sample line indicates:
Analysis of barcoded sample (BC16):  mysample1 
it should be instead
Analysis of barcoded sample (BC16):  mysample1:My16SDB

The "sample_id.txt" file should be formatted as follows:
RunName:20190802_x5 
RunDate:02.08.2019
# 	
BC16:mysample1:My16SDB
BC17:mysample2:My16SDB
BC18:mysample3:My16SDB
BC19:mysample4:My16SDB
BC22:mysample5:My16SDB
BC23:mysample6:My16SDB
BC24:mysample7:My16SDB
BC25:mysample8:My16SDB
BC26:mysample9:My16SDB
BC27:mysample10:My16SDB
BC28:mysample11:My16SDB
BC29:mysample12:My16SDB
BC30:mysample13:My16SDB

also your PDF does indicate correctly that the db could be read and that the FASTA file could be counted.
Yet, there is no information on the number of FASTA reads in your sample.
What is the content of the /1_fasta/ folder?
For BC16 for instance, the pipeline should produce 3 files:
-BC16.fasta
-BC16.fasta_mode_closest.fasta
-BC16_stats.txt

My BC16_stats.txt indicates:

```
Total sequences after porechop: 38
Summary of sequence lengths:
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
   49.0   457.2   469.5   449.8   476.8   522.0 

Number of sequences close to the mode (SCM): 11/38 (28.9%)
Summary of SCM lengths:
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  465.0   469.5   470.0   470.5   472.5   474.0 
```

**Comment by nbargues** [comment]
But your sample_id.txt from your Github is formatted like this :
RunName:20190802_x5
RunDate:02.08.2019

BC16:mysample1
BC17:mysample2
BC18:mysample3
BC19:mysample4
BC22:mysample5
BC23:mysample6
BC24:mysample7
BC25:mysample8
BC26:mysample9
BC27:mysample10
BC28:mysample11
BC29:mysample12
BC30:mysample13

So I will change this file and tell you if it changes anything.

For the /1_fasta folder I only have the BC**.fata file

**Comment by aramette** [comment]
Thanks. 
In version 1.8, BCXX:sampleName is the right format, as the db is provided by the -d flag.
In newer versions of LORCAN, the sample_id.txt should be BCXX:sampleName:databaseName
