### ISSUE TITLE
R1 step failed

### ISSUE THREAD

**Issue by CocoMlle** [aramette/LORCAN#5]
Hi,

I have issue just by running test with your test files, i get this error : 
(base) marine@curious:~/LORCAN/1.8/lib$ perl lorcan.pl -V -i /home/marine/LORCAN/1.8/example_files/input_test -o Output -L log_main.txt -I /home/marine/LORCAN/1.8/example_files/sample_id.txt -n 20 -m 10 -M 3000 -P 100 -D 5 -d My16SDB
OK: all arguments are present
current working directory: /home/marine/LORCAN/1.8/lib
	(i) readDIR:           /home/marine/LORCAN/1.8/example_files/input_test
	(I) sampleID:          /home/marine/LORCAN/1.8/example_files/sample_id.txt
	(o) Cdir:              Output
	(L) Main log name:     log_main.txt
	(n) NberThreads:       20
	(m) Min nber reads per BC: 10
	(M) Consensus MaxRead: 3000
	(P) Consensus MinRead: 100
	(D) delta:             5
	(d) DBchoice:          My16SDB
=> Checking script dependencies...
Checking db
	blastDBFile: 16S_stringent_custom.fasta
	blastDBFolder: /home/marine/LORCAN/1.8/example_files/BiBi/
Test db is ok (file found). Continuing...
Checking for Perl module dependencies:
OK               ... FindBin
OK               ... Cwd
OK               ... Parallel::ForkManager
OK               ... PDF::API2
OK ... All tests for script dependencies sucessfully done.
=> running R1_Seqkit...
sh: 1: cannot create Output/0_logs/1_initial_fastq_stats.txt: Directory nonexistent
!!! Missing file (exit!): 
	Output/0_logs/1_initial_fastq_stats.txt

Which is strange because i have folder Output/0_logs with log file ?? Do you have any idea to help me ? 
I run LORCAN on ubuntu 18
Thanks for your help :)
Marine

**Comment by aramette** [comment]
Hello,
The issue comes most likely from the fact that -o is not provided as an absolute path, but as a relative path.
-o full path to the output directory e.g. /path_to/output. The "output" directory folder is automatically created and appended to the indicated path.
See the usage example.
I hope it helps.
Best,
Alban
