### ISSUE TITLE
test-error at R4

### ISSUE THREAD

**Issue by tarah28** [aramette/LORCAN#6]
Hello! 
I have installed LORCAN but am getting an error and can't get past the R4 stage but I can't find anything in the log file to specifically tell my what dependency is missing or causing the exit. It seems to fail at creating a directory but I'm running this on a Linux workstation and I have permission to RW in that directory. 

WD=/home/programs/LORCAN/1.8/example_files
EF=/home/programs/LORCAN/1.8/example_files
FastqDir=$EF/input_test/

lorcan.pl -V -i $FastqDir -o $WD/myOutput -L log_main.txt -I $EF/sample_id.txt -n 12 -m 1 -M 1000 -P 100 -D 5 -d My16SDB

OK: all arguments are present
current working directory: /home/tlynch/programs/LORCAN/1.8/example_files
	(i) readDIR:           /home/tlynch/programs/LORCAN/1.8/example_files/input_test/
	(I) sampleID:          /home/tlynch/programs/LORCAN/1.8/example_files/sample_id.txt
	(o) Cdir:              /home/tlynch/programs/LORCAN/1.8/example_files/myOutput
	(L) Main log name:     log_main.txt
	(n) NberThreads:       12
	(m) Min nber reads per BC: 1
	(M) Consensus MaxRead: 1000
	(P) Consensus MinRead: 100
	(D) delta:             5
	(d) DBchoice:          My16SDB
=> (R0_Checking script dependencies) already completed
=> running R1_Seqkit...
[ERRO] /home/tlynch/programs/LORCAN/1.8/example_files/input_test/fastq_0.fastq.md5sum: fastx: invalid FASTA/Q format
=> running R2_porechop...
=> running R3_Seqkit_after_porechop...
=> running R4_parseMinNberReads...
ls: cannot access '/home/tlynch/programs/LORCAN/1.8/example_files/myOutput/2_individual_barcodes/': No such file or directory
R4_test2 failed. No directory created (exit)

Thanks!

**Comment by aramette** [comment]
The output indicates that at R1, a wrong format was detected. Because no file is processed, no barcode directory was created, which created a downstream error at R4.
