### ISSUE TITLE
error at R4

### ISSUE THREAD

**Issue by tarah28** [aramette/LORCAN#7]
Hello. Sorry to bother you again but I've tried to run it on the test data included with LORCAN and also with some of our data. The issue is the same - that it errors out at R4. I'm not sure why it's not producing the directories for the individual barcodes. Thank you in advance for your help!
OK: all arguments are present                                                                                                                                    
current working directory: /home/programs/LORCAN/1.8/example_files                                                                                        
 (i) readDIR:           /home/programs/LORCAN/1.8/example_files/input2/                                                                                   
 (I) sampleID:          /home/programs/LORCAN/1.8/example_files/sample_id2.txt                                                                            
 (o) Cdir:              /home/programs/LORCAN/1.8/example_files/myOut2                                                                                    
 (L) Main log name:     log_main2.txt                                                                                                                            
	(n) NberThreads:       12
	(m) Min nber reads per BC: 1
	(M) Consensus MaxRead: 1000
	(P) Consensus MinRead: 100
	(D) delta:             5
	(d) DBchoice:          My16SDB
=> (R0_Checking script dependencies) already completed
=> (R1_Seqkit) already completed
=> (R2_porechop) already completed
=> (R3_Seqkit_after_porechop) already completed
=> running R4_parseMinNberReads...
ls: cannot access '/home/programs/LORCAN/1.8/example_files/myOut2/2_individual_barcodes/': No such file or directory
R4_test2 failed. No directory created (exit)

[log_main.txt](https://github.com/aramette/LORCAN/files/11708561/log_main.txt)

**Comment by aramette** [comment]
Did you start from scratch again, i.e. by deleting all previously generated output folders and data? If not, when re-running the script with the same data and parameters, it may be that LORCAN skips some of the previous controls and error reporting, because these error messages have been now logged in the main log.
So the recommendation is to start re-running in another output directory or to delete the previously generated output directory.

**Comment by tarah28** [comment]
Thank you for the quick response. 
yes I did delete all of the previous output before running again.

**Comment by aramette** [comment]
Thanks.
So i suggest a last try using the suggested parameters from the help (-h)
-n 20 
-m 10 
-P 30 -D 5 -d BiBi16S

I also noticed that in the log_main.txt you provided (thank you), the log indicates that you are running in the same folder (the default behavior is to append to the previous log_main.txt file).
So maybe delete the whole output folder completely, before re-running LORCAN.

**Comment by tarah28** [comment]
Hi. I delete the entire output folder before attempting to run it again. I tried with the parameter suggestions you gave but it still exits at R4. 
I followed the instructions on the main github page to install version 1.8. 
I'm running it on Ubuntu 20.04. 
The pipeline looks like the analysis that we want to use but I'm not sure what else to try. I'm wondering if there is a dependency that is missing but I can't find any error message to suggest that. The message suggests a permission issue but it's running in my home directory so that shouldn't be the case. 
Thanks

**Comment by tarah28** [comment]
Made a bit of progress. I changed the directory of the output file and wrote out the command on the commandline (was running from bash script before). It ran further but not quite completed: 
lorcan.pl -V -i ~/programs/LORCAN/1.8/example_files/input_test/ -o ~/output_lorcan -L log_main.txt -I ~/programs/LORCAN/1.8/example_files/sample_id.txt -n 12 -m 10 -M 1000 -P 30 -D 5 -d ~/programs/LORCAN/DB/16S/BiBi/16S_stringent_custom.fasta
OK: all arguments are present
current working directory: ~/programs/LORCAN/1.8/example_files
	(i) readDIR:           ~/programs/LORCAN/1.8/example_files/input_test/
	(I) sampleID:          ~/programs/LORCAN/1.8/example_files/sample_id.txt
	(o) Cdir:              ~/output_lorcan
	(L) Main log name:     log_main.txt
	(n) NberThreads:       12
	(m) Min nber reads per BC: 10
	(M) Consensus MaxRead: 1000
	(P) Consensus MinRead: 30
	(D) delta:             5
	(d) DBchoice:         ~/programs/LORCAN/DB/16S/BiBi/16S_stringent_custom.fasta
=> (R0_Checking script dependencies) already completed
=> (R1_Seqkit) already completed
=> running R2_porechop...
=> running R3_Seqkit_after_porechop...
=> running R4_parseMinNberReads...
=> running R5_Extract_modal_sequences...
BC16 being processed
BC17 being processed
BC18 being processed
BC19 being processed
BC22 being processed
BC23 being processed
BC24 being processed
BC25 being processed
BC26 being processed
BC27 being processed
BC28 being processed
BC29 being processed
BC30 being processed
Error in library(seqinr) : there is no package called ‘seqinr’
Calls: capture.output ... withVisible -> suppressMessages -> withCallingHandlers -> library
Execution halted

Hopefully this helps figure out what's going on!
[log_main.txt](https://github.com/aramette/LORCAN/files/11728654/log_main.txt)

**Comment by aramette** [comment]
This looks already much better indeed. What you need to install is a R environment which contains seqinr.
Line 40 of config.pm, the R script being called should have the seqinr library pre-installed.
`our $Rscript 	="/software_conda/3/bin/Rscript";`

in the corresponding terminal while running R, you can install it using  `install.packages("seqinr")`.

**Comment by tarah28** [comment]
Getting SO close! 
A report is generated, but the BLAST and phylogenetic outputs in every individual sample directory are empty. Produced blank files. I doublechecked that all the correct versions and tools required are installed properly. All were installed with conda and seem to be working fine on their own but LORCAN doesn't seem to be using them. Thanks again for all of your help with this!

**Comment by aramette** [comment]
This is very strange that the script confirms that all dependencies (esp. BLAST, iqtree) are installed correctly, but there is then not output. If you could also post all the files in the 0_logs directory, this could help. Also from the [readme](https://github.com/aramette/LORCAN/tree/master/1.8#readme), the expected file output is listed. If you can tell which file you see or do not see, this could be another way to put the error in context. Thank you.

**Comment by tarah28** [comment]
Here's a screenshot to show what is in all the folders for one of the barcodes in the test dataset and the log files. Thanks for your help on this. 

[lorcan_output.pdf](https://github.com/aramette/LORCAN/files/11746951/lorcan_output.pdf)
[0_logs.zip](https://github.com/aramette/LORCAN/files/11746952/0_logs.zip)

**Comment by aramette** [comment]
I can see that BC30_consensus_sequences.fasta has a very small size (probably no sequence was produced). Hence, the BLAST files were then empty (as shown in your lorcan_output.pdf). So BLAST is working correctly indeed and the output shows that LORCAN uses correctly BLAST (generation of expected files) as expected. If only BC30 did not work, I would suggest that something in BC30 (number or quality of the reads) needs to be checked. LORCAN seems to work as expected from my understanding.

**Comment by tarah28** [comment]
Thanks for your help, much appreciated.
